# This is a basic workflow to help you get started with Actions

name: Team README

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.MY_PAT }}
          script: |
            // Get the list of members
            const team = github.rest.teams.getByName({
              org: "${{ secrets.TEAM_ORG_NAME }}",
              team_slug: "${{ secrets.TEAM_SLUG }}"
            });
            // Format the list of members as a markdown table containing their name and avatar
            const members = team.data.members.map(member => {
              return `| ${member.login} | ![${member.login} avatar](${member.avatar_url}) |`;
            });
            // Update the README.md file
            github.rest.repos.createOrUpdateFileContents({
              owner: "${{ secrets.TEAM_ORG_NAME }}",
              repo: "${{ secrets.TEAM_SLUG }}",
              path: "README.md",
              message: "Update README.md",
              content: Buffer.from(`# ${team.data.name}
