name: "Team README table generator"

on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      org:
        description: 'The organization to run the workflow against'
        required: true
        default: 'my-org'
      team:
        description: 'The team to run the workflow against'
        required: true
        default: 'my-team'

jobs:
  run_team_readme_job:
    runs-on: ubuntu-latest
    name: Run team readme generator
    steps:
      - uses: actions/checkout@v4
      - id: Generate
        uses: djdefi/team-readme-generator@main
        with:
          org: ${{ github.event.inputs.org }}
          team: ${{ github.event.inputs.team }}
          my-pat: ${{ secrets.MY_PAT }}
