# This is a basic workflow to help you get started with Actions

name: Team README

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.MY_PAT }}
          result-encoding: string
          script: |
            // Get the list of members
            const team = await github.rest.teams.getByName({
              org: "NevadaCountyFreeCodeCamp",
              team_slug: "Campers"
            });
            // Log the list of members to the console
            console.log(team);
            console.log(team.data);
            // Get the list of members on the team
            const members = await github.rest.teams.listMembersInOrg({
              org: "NevadaCountyFreeCodeCamp",
              team_slug: "Campers"
            });
            // Log the list of members to the console
            console.log(members);
            console.log(members.data);
            // For each member returned, use the user api to get their login, avatar, location, and bio
            const memberData = await Promise.all(members.data.map(async (member) => {
              const user = github.rest.users.getByUsername({
                username: member.login
              });
              return {
                login: user.data.login,
                avatar: user.data.avatar_url,
                location: user.data.location,
                bio: user.data.bio
              };
            }));
            // Log the member data to the console
            console.log(memberData);
