# This is a basic workflow to help you get started with Actions

name: Team README

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.MY_PAT }}
          script: |
            // Get the list of members
            const team = await github.rest.teams.getByName({
              org: "NevadaCountyFreeCodeCamp",
              team_slug: "Campers"
            });
            // Log the list of members to the console
            console.log(team);
            console.log(team.data);
            // Get the list of members on the team
            const members = await github.rest.teams.listMembersInOrg({
              org: "NevadaCountyFreeCodeCamp",
              team_slug: "Campers"
            });
            // Log the list of members to the console
            console.log(members);
            console.log(members.data);
            // For each member returned, use the user api to get their login, avatar, location, and bio
            // Format the data into a markdown table
            const table = members.data.map(member => {
              const user = await github.rest.users.getByUsername({
                username: member.login
                console.log(user);
              });
              return `| <img src="${user.data.avatar_url}" width="50" height="50" /> | ${user.data.login} | ${user.data.location} | ${user.data.bio} |`;
            });
            // Log the table to the console
            console.log(table);

